version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - antfu
  - apeira
  - bumpp
  - changelogithub
  - eslintcache
  - kwaa
  - masknet
  - moeru
  - ollama
  - pkgroll
  - qwen
  - vitest
  - xsai
ignoreWords: []
import: []
