version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - agui
  - antfu
  - apeira
  - apos
  - bumpp
  - ccardlib
  - changelogithub
  - chara
  - charx
  - clsx
  - demi
  - dotenv
  - duckduckgo
  - earendil
  - esbuild
  - eslintcache
  - flac
  - hitl
  - KHTML
  - kwaa
  - lucide
  - masknet
  - moeru
  - ollama
  - pkgroll
  - qwen
  - risu
  - risuai
  - shadcn
  - shiki
  - shikijs
  - sonarjs
  - unocss
  - vite
  - vitejs
  - vitepress
  - vitest
  - xsai
  - xsschema
  - yocto
ignoreWords: []
import: []
