version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - agui
  - antfu
  - apeira
  - bumpp
  - changelogithub
  - earendil
  - eslintcache
  - flac
  - kwaa
  - masknet
  - moeru
  - ollama
  - pkgroll
  - qwen
  - sonarjs
  - vite
  - vitejs
  - vitepress
  - vitest
  - xsai
  - yocto
ignoreWords: []
import: []
