shellEmulator: true

trustPolicy: no-downgrade

packages:
  - docs
  - examples/*
  - packages/*

catalog:
  '@ag-ui/core': ^0.0.53
  '@antfu/eslint-config': ^8.2.0
  '@copilotkit/react-core': ^1.57.1
  '@copilotkit/react-ui': ^1.57.1
  '@earendil-works/pi-tui': ^0.75.3
  '@moeru/eslint-config': &std ^0.1.0-beta.18
  '@moeru/std': *std
  '@moeru/tsconfig': *std
  '@types/node': ^25.6.2
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^6.0.1
  '@xsai/tool': 0.5.0-beta.4
  bumpp: ^11.1.0
  eslint: ^10.3.0
  foxact: ^0.3.4
  pkgroll: ^2.27.0
  react: ^19.2.6
  react-dom: ^19.2.6
  rxjs: ^7.8.1
  tsx: ^4.21.0
  typescript: ~6.0.3
  unstorage: ^1.17.5
  vite: ^8.0.13
  vitepress: ^2.0.0-alpha.17
  vitest: ^4.1.6
  yocto-queue: ^1.2.2
  zod: ^4.4.3

catalogs:
  xsai:
    '@xsai-ext/responses': &xsai ^0.5.0-beta.4
    '@xsai/shared': *xsai
    '@xsai/shared-chat': *xsai
