shellEmulator: true

trustPolicy: no-downgrade

packages:
  - docs
  - examples/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^8.2.0
  '@moeru/eslint-config': &std ^0.1.0-beta.18
  '@moeru/tsconfig': *std
  '@types/node': ^25.6.2
  bumpp: ^11.1.0
  eslint: ^10.3.0
  p-limit: ^7.3.0
  pkgroll: ^2.27.0
  tsx: ^4.21.0
  typescript: ~6.0.3

catalogs:
  xsai:
    '@xsai-ext/responses': &xsai ^0.5.0-beta.4
    '@xsai/shared': *xsai
    '@xsai/shared-chat': *xsai
